steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '.'
    ]
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/test-case-builder']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'beta',
    'run',
    'deploy',
    '--allow-unauthenticated',
    'test-case-builder',
    '--image',
    'gcr.io/$PROJECT_ID/test-case-builder'
    ]
images:
- gcr.io/$PROJECT_ID/test-case-builder
​